"""Initial schema with all models

Revision ID: a5fe95a4fca0
Revises:
Create Date: 2025-10-08 15:15:02.932259

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5fe95a4fca0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "motorcycles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("make", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("displacement_cc", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("msrp", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("specs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_motorcycle_make_model_year", "motorcycles", ["make", "model", "year"], unique=False
    )
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("motorcycle_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("mileage", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("location_city", sa.String(length=100), nullable=True),
        sa.Column("location_state", sa.String(length=50), nullable=True),
        sa.Column("location_zip", sa.String(length=10), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("seller_type", sa.String(length=50), nullable=True),
        sa.Column("title_status", sa.String(length=50), nullable=True),
        sa.Column("condition", sa.String(length=50), nullable=True),
        sa.Column("modifications", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("scraped_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["motorcycle_id"],
            ["motorcycles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index("idx_listing_active", "listings", ["is_active"], unique=False)
    op.create_index("idx_listing_price", "listings", ["price"], unique=False)
    op.create_index("idx_listing_scraped_at", "listings", ["scraped_at"], unique=False)
    op.create_index("idx_listing_source", "listings", ["source"], unique=False)
    op.create_index("idx_listing_year_make", "listings", ["year", "motorcycle_id"], unique=False)
    op.create_table(
        "price_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("motorcycle_id", sa.Integer(), nullable=False),
        sa.Column("avg_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("median_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("min_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("max_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["motorcycle_id"],
            ["motorcycles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_price_history_motorcycle_date",
        "price_history",
        ["motorcycle_id", "date"],
        unique=False,
    )
    op.create_table(
        "evaluations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("overall_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("letter_grade", sa.String(length=2), nullable=True),
        sa.Column("price_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("mileage_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("quality_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("condition_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("red_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("recommendations", sa.Text(), nullable=True),
        sa.Column("comparable_listings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evaluated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_evaluation_listing", "evaluations", ["listing_id"], unique=False)
    op.create_index("idx_evaluation_score", "evaluations", ["overall_score"], unique=False)
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("ai_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("analyzed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_image_listing", "images", ["listing_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_image_listing", table_name="images")
    op.drop_table("images")
    op.drop_index("idx_evaluation_score", table_name="evaluations")
    op.drop_index("idx_evaluation_listing", table_name="evaluations")
    op.drop_table("evaluations")
    op.drop_index("idx_price_history_motorcycle_date", table_name="price_history")
    op.drop_table("price_history")
    op.drop_index("idx_listing_year_make", table_name="listings")
    op.drop_index("idx_listing_source", table_name="listings")
    op.drop_index("idx_listing_scraped_at", table_name="listings")
    op.drop_index("idx_listing_price", table_name="listings")
    op.drop_index("idx_listing_active", table_name="listings")
    op.drop_table("listings")
    op.drop_index("idx_motorcycle_make_model_year", table_name="motorcycles")
    op.drop_table("motorcycles")
    # ### end Alembic commands ###
